spring.application.name=destinos-api-viagens

# Porta do servidor embutido (padrao 8080)
server.port=8080

# Formatacao mais legivel do JSON de resposta durante o desenvolvimento
spring.jackson.serialization.indent-output=true
